# Generated by Django 2.1 on 2018-08-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailwiz', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(),
        ),
    ]
