# Generated by Django 2.1 on 2018-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailwiz', '0003_auto_20180827_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(max_length=100),
        ),
    ]
